version: "3"
services:
  aliwaf-autoblacklist:
    build:
      context: .
    image: aliwaf-autoblacklist
    environment:
      accessKeyId: xxx
      accessSecret: xxx
      KeyPrefix: super_blacklist:*
      redisURL: redis://redis:6379/0
      Interval: 2
    volumes:
    - "./logs:/srv/logs"
  redis:
    image: redis:3.2-alpine